# Cloud Build configuration for LaxAI
# Builds Docker image, pushes to Artifact Registry and deploys to Cloud Run.

substitutions:
  # Build-time and deployment substitutions. Override these when calling `gcloud builds`
  # or when creating a build trigger.
  _IMAGE: "laxai"
  _REQS: "requirements-cpu.txt"        # maps from docker-compose build arg REQS   
  _CLOUD_RUN_SERVICE: "laxai-gpu"
  _CLOUD_RUN_REGION: "us-central1"
  _DEPLOY_TO_CLOUD_RUN: "true"       # set to "true" to run the deploy step
  

steps:
  # Build the final production image, tagging it with only "latest".
  - id: "build-and-tag-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/laxai-repo/${_IMAGE}:latest"
      - "--build-arg"
      - "REQS=${_REQS}"
      - "--build-arg"
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
      - "."

  # Push the :latest tag only.
  - id: "push-latest-image"
    name: "gcr.io/cloud-builders/docker"
    args: 
      - "push" 
      - "us-central1-docker.pkg.dev/$PROJECT_ID/laxai-repo/${_IMAGE}:latest"

  # Deploy to Cloud Run using the "latest" tag and the correct flags for resources.
  - id: "deploy-to-cloud-run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "${_DEPLOY_TO_CLOUD_RUN}" == "true" ]]; then
          echo "Deploying to Cloud Run: ${_CLOUD_RUN_SERVICE} (${_CLOUD_RUN_REGION})"
          gcloud run deploy "${_CLOUD_RUN_SERVICE}" \
            --image="us-central1-docker.pkg.dev/$PROJECT_ID/laxai-repo/${_IMAGE}:latest" \
            --region="${_CLOUD_RUN_REGION}" \
            --platform=managed \
            --allow-unauthenticated \
            --quiet \
            --cpu="4000m" \
            --memory="16Gi" \
            --service-account="googlebatch@laxai-466119.iam.gserviceaccount.com"
        else
          echo "Skipping Cloud Run deployment because _DEPLOY_TO_CLOUD_RUN != true"
        fi

# Images to be built and pushed to Artifact Registry
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/laxai-repo/${_IMAGE}:latest"

# Note: The serviceAccountName is specified as a flag in gcloud run deploy
# and no longer needed here.

# Optional: make a secret available from Secret Manager to build steps.
# Replace the versionName below with the actual secret resource name.
availableSecrets:
  secretManager: []

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "3600s"  # 60 minutes
