# Cloud Build configuration for LaxAI
# Builds Docker image, optional tests, pushes to Container Registry and can deploy to Cloud Run.

substitutions:
  # _IMAGE should be just the image name; the PROJECT_ID built-in substitution
  # will be used at the call sites to avoid nested/unexpanded variables.
  _IMAGE: "laxai"
  _DEPLOY_TO_CLOUD_RUN: "false" # set to "true" in trigger to deploy
  _CLOUD_RUN_SERVICE: "laxai-api"
  _CLOUD_RUN_REGION: "us-central1"

steps:
  # Build a test image with dev/test dependencies (using docker builder)
  - id: "build-test-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/${_IMAGE}:test-${SHORT_SHA}"
      - --build-arg
      - "INSTALL_TEST_DEPS=true"
      - .

  # Run tests inside the test image
  - id: "run-tests-in-image"
    name: "gcr.io/cloud-builders/docker"
    args: ["run", "--rm", "gcr.io/$PROJECT_ID/${_IMAGE}:test-${SHORT_SHA}", "pytest", "-q"]

  # Build the final production image (no test deps)
  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/${_IMAGE}:${SHORT_SHA}"
      - .

  # Push the final image to Container Registry
  - id: "push-image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE}:${SHORT_SHA}"]

  - id: "maybe-cloud-run-deploy"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/bash"
    args:
      - -c
      - |
        set -euo pipefail
        if [ "${_DEPLOY_TO_CLOUD_RUN}" = "true" ]; then
          echo "Deploying to Cloud Run: ${_CLOUD_RUN_SERVICE} in ${_CLOUD_RUN_REGION}"
          gcloud run deploy "${_CLOUD_RUN_SERVICE}" \
            --image "gcr.io/$PROJECT_ID/${_IMAGE}:${SHORT_SHA}" \
            --region "${_CLOUD_RUN_REGION}" \
            --platform managed \
            --allow-unauthenticated
        else
          echo "Skipping Cloud Run deploy (set _DEPLOY_TO_CLOUD_RUN to 'true' to enable)"
        fi

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
  # Increase machine type to provide more memory/CPU for Kaniko builds (avoid OOM 137)
  machineType: "E2_HIGHCPU_8"

timeout: "3600s"  # 60 minutes

# Notes:
# - Use substitutions to customize behavior when creating a build trigger.
# - Example gcloud submit (uses docker build locally):
#   gcloud builds submit --config cloudbuild.yaml --substitutions=_SKIP_TESTS=false,_DEPLOY_TO_CLOUD_RUN=false
