# LaxAI Configuration File
# This file defines all configuration for the LaxAI training pipeline

[secrets]
# Secret Manager configuration
# Maps environment variable names to their corresponding Secret Manager secret names
# Format: environment_variable = ["primary_secret_name", "alternative_secret_name"]

WANDB_API_KEY = ["wandb-api-key", "WANDB_API_KEY"]

# Add more secrets as needed for your project
# EXAMPLE_API_KEY = ["example-api-key", "EXAMPLE_API_KEY"]

[environment]
# Environment-specific configuration
default_project_env_vars = ["GOOGLE_CLOUD_PROJECT", "GCLOUD_PROJECT", "GCP_PROJECT"]
metadata_timeout = 2  # seconds
metadata_base_url = "http://metadata.google.internal/computeMetadata/v1"

[logging]
# Logging configuration
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
