# LaxAI Configuration File
# This file defines all configuration for the LaxAI training pipeline

[secrets]
# Secret Manager configuration
# List environment variable names that should be loaded from the environment
# or (if missing) retrieved from Secret Manager under the same secret name.
secrets = ["WANDB_API_KEY", "HUGGINGFACE_HUB_TOKEN"]

# Add more secrets as needed for your project
# EXAMPLE_API_KEY = ["example-api-key", "EXAMPLE_API_KEY"]


[environment]
# Environment-specific configuration
default_project_env_vars = ["GOOGLE_CLOUD_PROJECT", "GCLOUD_PROJECT", "GCP_PROJECT"]
metadata_base_url = "http://metadata.google.internal/computeMetadata/v1"
GOOGLE_APPLICATION_CREDENTIALS = ["GOOGLE_APPLICATION_CREDENTIALS", "google-application-credentials"]

[logging]
# Logging configuration
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
