services:
  train:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQS: requirements-gpu.txt
        INSTALL_GCLOUD: "false"
        GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT:-laxai-466119}"
    image: laxai:local-test
    ports:
      - "${PORT:-8000}:8000"
    environment:
      PORT: "${PORT:-8000}"
      GOOGLE_CLOUD_PROJECT: "${GOOGLE_CLOUD_PROJECT:-laxai-466119}"
      # By default the app looks for GOOGLE_APPLICATION_CREDENTIALS; mount the
      # host key file to /run/secrets/gcloud/key.json and set this env var.
      GOOGLE_APPLICATION_CREDENTIALS: "/run/secrets/gcloud/key.json"
    # Optional: mount your service account key from the host. Replace the host path below
    # with the actual path to your JSON key. Keep the mount read-only (:ro).
    volumes:
      - /Users/fernandomousinho/Documents/Learning_to_Code/Vault/laxai-466119-5454645432ff.json:/run/secrets/gcloud/key.json:ro
    restart: unless-stopped
