############################################################################
#                                                                          #
#                    SIMPLIFIED BUILDER FOR API LAYERS                     #
#                                                                          #
############################################################################

# This Cloud Build file builds a Docker image, pushes it to Artifact
# Registry, and deploys it to a CPU-based Cloud Run service.

substitutions:
  _GOOGLE_CLOUD_PROJECT: "laxai-466119"
  # Note: Cloud Build does not expand nested substitutions inside substitution values.
  # Use the literal project id here to avoid unresolved ${_GOOGLE_CLOUD_PROJECT} in the email.
  _SERVICE_ACCOUNT: "googlebatch@laxai-466119.iam.gserviceaccount.com"
  _WORK_DIR: "services/service_api"
  _SERVICE_DATAPREP_NAME: "laxai-service-dataprep"
  _SERVICE_DATAPREP_PORT: "80"
  _SERVICE_DATAPREP_URL: "https://laxai-service-dataprep-517529966392.us-central1.run.app/"

steps:
  - id: "build-and-tag-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "${_WORK_DIR}/Dockerfile"
      - "-t"
      - "us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-api:latest"
      - "--build-arg"
      - "REQS=requirements-cloud.txt"
      - "--build-arg"
      - "GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT}"
      - "."

  - id: "push-latest-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-api:latest"

  - id: "deploy-to-cloud-run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "laxai-api"
      - "--image=us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-api:latest"
      - "--region=us-central1"
      - "--cpu=1"
      - "--memory=512Mi"
      - "--min-instances=0"
      - "--cpu-throttling"
      - "--max-instances=2"
      - "--timeout=300s"
      - "--concurrency=10"
      - "--service-account=${_SERVICE_ACCOUNT}"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT},SERVICE_DATAPREP_NAME=${_SERVICE_DATAPREP_NAME},SERVICE_DATAPREP_PORT=${_SERVICE_DATAPREP_PORT}, SERVICE_DATAPREP_URL=${_SERVICE_DATAPREP_URL}"
      - "--no-allow-unauthenticated"
      - "--quiet"

images:
  - "us-central1-docker.pkg.dev/${_GOOGLE_CLOUD_PROJECT}/laxai-repo/laxai-api:latest"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "3600s"
