############################################################################
#                                                                          #
#               CLOUD FUNCTIONS BUILDER FOR TRAINING PROXY                #
#                                                                          #
############################################################################

# This Cloud Build file deploys the training proxy as a Cloud Function
# triggered by Pub/Sub messages. Much more cost-effective than always-on Cloud Run.

substitutions:
  _GOOGLE_CLOUD_PROJECT: "laxai-466119"
  _SERVICE_ACCOUNT: "googlebatch@${_GOOGLE_CLOUD_PROJECT}.iam.gserviceaccount.com"
  _FUNCTION_NAME: "laxai-training-proxy"
  _REGION: "us-central1"
  _SOURCE_DIR: "services/service_cr_train_proxy"

steps:
  - id: "deploy-cloud-function"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "functions"
      - "deploy"
      - "${_FUNCTION_NAME}"
      - "--region=${_REGION}"
      - "--runtime=python312"
      - "--source=${_SOURCE_DIR}"
      - "--entry-point=process_pubsub_message"
      - "--trigger-topic=training-jobs"
      - "--service-account=${_SERVICE_ACCOUNT}"
      - "--set-env-vars=GOOGLE_CLOUD_PROJECT=${_GOOGLE_CLOUD_PROJECT},CLOUD_REGION=${_REGION}"
      - "--memory=512MB"
      - "--timeout=540s" # 9 minutes max for Cloud Functions
      - "--max-instances=10"
      - "--quiet"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1800s"
