gcs:
  bucket_name: "laxai_dev"
  tenant_id: "{tenant_id}"
  data_prefixes:
    raw_data: "raw/"
    imported_video: "process/{video_id}/imported/"
    extracted_frames: "process/{video_id}/{frame_id}/"
    orig_crops: "process/{video_id}/{frame_id}/orig_crops/"
    augmented_crops: "process/{video_id}/{frame_id}/augmented_crops/{orig_crop_id}"
    datasets_root: "datasets"
    train_dataset: "datasets/{dataset_id}/train"
    val_dataset: "datasets/{dataset_id}/val"
    run_data: "runs/{run_id}/"